name: Deploy React to Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v20
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Build and Run Docker Containers
        run: docker compose up --build -d
